scripts:
  - name: Nuclear Fix
    script: |
      # 1. Purana sara kachra saaf karo
      rm -rf android/app/src/main/kotlin/com/abhi/dhunly
      mkdir -p android/app/src/main/kotlin/com/abhi/dhunly
      
      # 2. Sahi file zabardasti likho
      echo 'package com.abhi.dhunly
      import io.flutter.embedding.android.FlutterActivity
      class MainActivity: FlutterActivity() { }' > android/app/src/main/kotlin/com/abhi/dhunly/MainActivity.kt
      
      # 3. Flutter clean zaroori hai
      flutter clean
      flutter pub get
  - name: Build APK
    script: |
      flutter build apk --debug --android-skip-build-dependency-validation
