name: dhunly_app
description: "Dhunly Online Music App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  just_audio: ^0.9.36
  audio_video_progress_bar: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/logo.png"
  adaptive_icon_background: "#121212"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
