name: dhunly_pro
description: "Dhunly Pro Official"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Ye tool logo banayega
  flutter_launcher_icons: "^0.13.1"

# Logo ki sahi setting
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
