name: dhunly_pro
description: Modern Music Streaming App
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  http: ^1.1.0
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
