apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace "com.abhi.dhunly"
    compileSdkVersion 33
    defaultConfig {
        applicationId "com.abhi.dhunly"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
    }
}
